//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTest.WebServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnicalTest.WebServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se eliminó correctamente.
        /// </summary>
        internal static string MSGDELETE {
            get {
                return ResourceManager.GetString("MSGDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un registro con el nombre {0} en la base de datos.
        /// </summary>
        internal static string MSGEXIST {
            get {
                return ResourceManager.GetString("MSGEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el ID de la raza seleccionada.
        /// </summary>
        internal static string MSGINVALIDRACE {
            get {
                return ResourceManager.GetString("MSGINVALIDRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún registro.
        /// </summary>
        internal static string MSGNOFOUND {
            get {
                return ResourceManager.GetString("MSGNOFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creó exitosamente el registro.
        /// </summary>
        internal static string MSGSAVE {
            get {
                return ResourceManager.GetString("MSGSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se actualizó correctamente.
        /// </summary>
        internal static string MSGUPDATE {
            get {
                return ResourceManager.GetString("MSGUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro estado debe ser true o false.
        /// </summary>
        internal static string MSGVALIDATEBOOL {
            get {
                return ResourceManager.GetString("MSGVALIDATEBOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha ingresada debe ser en formato dd/mm/yyyy.
        /// </summary>
        internal static string MSGVALIDATEDATE {
            get {
                return ResourceManager.GetString("MSGVALIDATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún registro para eliminar para el Id {0}.
        /// </summary>
        internal static string MSGVALIDATEDELETE {
            get {
                return ResourceManager.GetString("MSGVALIDATEDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se admiten valores M para Macho o H para Hembra.
        /// </summary>
        internal static string MSGVALIDATEGENDER {
            get {
                return ResourceManager.GetString("MSGVALIDATEGENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro nombre es obligado.
        /// </summary>
        internal static string MSGVALIDATENAME {
            get {
                return ResourceManager.GetString("MSGVALIDATENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor ingresado debe ser mayor a cero.
        /// </summary>
        internal static string MSGVALIDATENUMBER {
            get {
                return ResourceManager.GetString("MSGVALIDATENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio debe ser mayor a cero.
        /// </summary>
        internal static string MSGVALIDATEPRICE {
            get {
                return ResourceManager.GetString("MSGVALIDATEPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún registro para actualizar para el Id {0}.
        /// </summary>
        internal static string MSGVALIDATEUPDATE {
            get {
                return ResourceManager.GetString("MSGVALIDATEUPDATE", resourceCulture);
            }
        }
    }
}
